I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 38, in script
    init python:
  File "game/script.rpy", line 48, in <module>
    class CharacterStats(BaseStatsObject):
NameError: name 'BaseStatsObject' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 38, in script
    init python:
  File "/Users/princesssteffykins/Downloads/RENPY PROJECTS/renpy-7.2.2-sdk/renpy/ast.py", line 900, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/princesssteffykins/Downloads/RENPY PROJECTS/renpy-7.2.2-sdk/renpy/python.py", line 1930, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 48, in <module>
    class CharacterStats(BaseStatsObject):
NameError: name 'BaseStatsObject' is not defined

Darwin-17.7.0-x86_64-i386-64bit
Ren'Py 7.2.2.491
TestNovel1 1.0
Tue Sep  3 10:36:21 2019
